services:

  app:
    build: .
    init: true
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  banco:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
